# Generated by Django 4.2.3 on 2023-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_user_cred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cred',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
