# Generated by Django 4.2.3 on 2023-08-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_alter_user_cred_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(),
        ),
    ]
