# Generated by Django 4.2.3 on 2023-08-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Images/'),
        ),
    ]
