# Generated by Django 4.2.3 on 2023-08-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
