# Generated by Django 4.2.3 on 2023-08-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_alter_card_idproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='idProduct',
            new_name='productId',
        ),
    ]
