# Generated by Django 4.2.3 on 2023-08-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_rename_idproduct_card_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='productId',
        ),
    ]
