# Generated by Django 4.2.3 on 2023-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_remove_card_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='productId',
            field=models.IntegerField(blank=-1, default=1),
            preserve_default=False,
        ),
    ]
