# Generated by Django 4.2.3 on 2023-08-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_card_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='productId',
            field=models.IntegerField(),
        ),
    ]
