# Generated by Django 4.2.3 on 2023-08-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_card_email_alter_card_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('locality', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
